tests/test_ssl.py: FTP/TLS fails if socket.setdefaulttimeout() is called
https://bugzilla.osafoundation.org/show_bug.cgi?id=2341

Also, fixing BIO tests.

 * fewer test failures for python3, and still passes the python2 tests
 * remove duplicate tests definition.
 * attempt to add socket's recv_into.

    Still doesn't work:

     $ python3 -munittest -v tests.test_ssl.HttpslibSSLClientTestCase.test_HTTPSConnection
    test_HTTPSConnection (tests.test_ssl.HttpslibSSLClientTestCase) ... ERROR

    ======================================================================
    ERROR: test_HTTPSConnection (tests.test_ssl.HttpslibSSLClientTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/matej/archiv/knihovna/repos/m2crypto/tests/test_ssl.py", line 176, in test_HTTPSConnection
        data = c.getresponse().read()
      File "/usr/lib64/python3.4/http/client.py", line 1171, in getresponse
        response.begin()
      File "/usr/lib64/python3.4/http/client.py", line 351, in begin
        version, status, reason = self._read_status()
      File "/usr/lib64/python3.4/http/client.py", line 333, in _read_status
        raise BadStatusLine(line)
    http.client.BadStatusLine: