Add everything to Rand module.
Still doesn't work:

    $ python -munittest -v tests.test_rand
    tests.test_randtest_bytes (tests.test_rand.DummyRandTestCase) ... ERROR
    test_load_save (tests.test_rand.DummyRandTestCase) ... ok
    test_seed_add (tests.test_rand.DummyRandTestCase) ... ERROR
    test_bytes (tests.test_rand.RandTestCase) ... ok
    test_load_save (tests.test_rand.RandTestCase) ... ok
    test_pseudo_bytes (tests.test_rand.RandTestCase) ... ok
    test_seed_add (tests.test_rand.RandTestCase) ... ok

    ======================================================================
    ERROR: test_bytes (tests.test_rand.DummyRandTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/test_rand.py", line 54, in test_bytes
        Rand.dummyrand_bytes(-1)
    TypeError: dummyrand_bytes expected 2 arguments, got 1

    ======================================================================
    ERROR: test_seed_add (tests.test_rand.DummyRandTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "tests/test_rand.py", line 68, in test_seed_add
        self.assertIsNone(Rand.dummyrand_seed(os.urandom(1024)))
    TypeError: dummyrand_seed expected 2 arguments, got 1

    ----------------------------------------------------------------------
    Ran 7 tests in 0.001s

    FAILED (errors=2)
    $

The problem is that the C module expects C-style calling with two real
paramters (char-buffer, length) and doesn't translate from Python bytes
and back.